services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: ["/entrypoint.sh"]
    # для быстрых правок кода в локалке раскомментируй volume:
    # volumes:
    #   - ./project:/app/project:delegated

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis
    working_dir: /app/project
    command: ["celery", "-A", "project", "worker", "-l", "info"]
    # volumes:
    #   - ./project:/app/project:delegated

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME:-nlc_db}
      POSTGRES_USER: ${DB_USER:-nlc_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-nlc_password}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

volumes:
  pgdata:
