# Generated by Django 5.2.5 on 2025-08-31 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ("id",)},
        ),
    ]
